filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
#output.kafka:
#  hosts: ["broker:9092"]
#  topic: "devopslab"
#  codec.json: 
#    pretty: false

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  filebeat.modules:
    - module: system
    - module: kafka
    - module: nginx
    
setup.kibana:
  host: "kib:5601"
