###########################################################
# Define inputs to Filebeat
# Multiple inputs are allowed
###########################################################
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log

###########################################################
# Define output of the Filebeat.
# ONLY ONE OUTPUT PER FILEBEAT INSTANCE IS ALLOWED
###########################################################
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
#output.kafka:
#  hosts: ["broker:19092"]
#  topic: "devopslab"
#  required_ack: -1
#  codec.format:
#    string: '%{[timestamp]} %{[message]}'
#  codec.json: 
#    pretty: false

###########################################################
# Define standard predefined sources
###########################################################
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

filebeat.modules:
    - module: system
    - module: kafka
    - module: nginx
    
###########################################################
# Define kibana for auto dashboard setup import (optional)
###########################################################
setup.kibana:
  host: "kib:5601"
